export const users = [
    "zena.huels@gmail.com",
    "weich.lauren@gmail.com",
    "tillman.marisa@gmail.com",
    "mariela.lesch@gmail.com",
    "abshire.bertrand@gmail.com",
    "biedner@hotmai.com",
    "skreiger@jacobs.biz",
    "dbrakus@yahoo.com",
    "tyra.heidenreich@gmail.com",
    "vwehner@tremblay.com",
    "kessler.eugene@gmail.com",
    "murray.spencer@wisozk.info",
    "toby63@weich.com",
    "rashawn51@yahoo.com",
    "keisi.crona@crona.net",
    "kebler.monty@mann.com",
    "bianda.rhett@gaylord.com",
    "lebsack.kristy@hotmail.com",
    "bridget33@schuster.com",
    "herzog.maymie@wehner.com",
    "ashleigh10@ghotmail.com",
    "weber.sister@yahoo.com",
    "ipfeffer@hotmail.com",
    "derek60@hotmail.com",
    "west.jude@weber.info",
    "eschneider@hintz.biz",
    "evalyn52@goodwin.biz",
    "barret.auer@wilderman.com",
    "lehner.dayton@yahoo.com",
    "prohaska.britney@hansen.com",
    "christiana59@huels.com",
    "jgerhold@yahoo.com",
    "santino63@bashirian.com",
    "kennith.buckridge@gmail.com",
    "zgoodwin@hotmail.com",
    "jaguan.stark@hotmail.com",
    "raynor.juels@brown.com",
    "curt.johnson@wisozck.com",
    "felton96@wisoky.com",
    "michelle24@hammes.com",
    "nkoeplin@bernhard.com",
    "araceli.goyette@yahoo.com",
    "hrutherford@gmail.com",
    "qschiller@gdenesik.com",
    "rico.mayer@yahoo.com",
    "amari90@hotmail.com",
    "bframi@gmail.com",
    "fadel.kendall@ward.com",
    "rafael.uptom@gmail.com",
];

export const actions = [
    "Create Client",
    "Create User",
    "Edit Client",
    "Edit User",
    "Change Profile Info",
    "Delete User",
    "Delete Client",
    "Deactivate Client",
    "Activate User",
    "Activate Client",
    "Log In",
    "Bulk Activate",
    "Bulk Deactivate",
    "Bulk Delete",
    "Log In As User",
    "Log Out As User",
    "Change Password",
    "Initiate Password Reset",
    "Simple Search",
    "Advanced Search",
    "Export to PST",
    "Export to EML",
    "Export to PDF",
    "Download Email",
    "Download Email Attachment",
    "Restore Email",
    "Forward Email",
    "Reply to Email",
    "Reply to All",
    "Ingest Imported Files",
    "Bulk Export Emails as PDF",
    "Bulk Export Emails as EML",
    "Bulk Export Email as PST",
    "Export All as PDF",
    "Export All as EML",
    "Export All as PST",
    "Bulk Download Emails",
    "Bulk Restore Emails",
    "Create Personal Tag",
    "Create Legal Hold Tag",
    "Create Retention Tag",
    "Edit Personal Tag",
    "Edit Legal Hold Tag",
    "Edit Retention Tag",
    "Delete Personal Tag",
    "Delete Legal Hold Tag",
    "Delete Retention Tag",
    "Assign Personal Tag",
    "Assign Legal Hold Tag",
    "Remove Legal Hold Tag",
    "Remove Personal tag",
    "Bulk Remove Personal Tag",
    "Bulk Remove Legal Hold Tag",
    "Save Simple Search",
    "Save Advanced Search",
    "Delete Saved Search",
    "Delete Recent Simple Search",
    "Delete Recent Advanced Search",
];